# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-21 13:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='tweet_text',
            field=models.TextField(),
        ),
    ]
