# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-21 20:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_auto_20160621_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='tweet_id',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
